import frappe
import json
from frappe import _


@frappe.whitelist(allow_guest = True)
def get_material_code_from_sap():
    print("--------------------API GOT HIT IN SAP---------------")
    try:
        data = frappe.request.get_json()
        # print("SAP Data=====>",data)
        if not data:
            return {"status": "fail", "message": "No JSON body received"}

        reqno = data.get("Reqno")
        matnr = data.get("Matnr")
        maktx = data.get("Maktx")
        zmsg = data.get("Zmsg")
        ztext = data.get("Ztext")

        if not reqno or not matnr:
            return {"status": "fail", "message": "Reqno and Matnr are required fields"}

        requestor_doc = frappe.get_doc("Requestor Master", {"request_id": reqno})
        if not requestor_doc:
            return {"status": "fail", "message": f"No Requestor Master found for request_id: {reqno}"}

        material_master_name = requestor_doc.material_master_ref_no
        material_doc = frappe.get_doc("Material Master", material_master_name)

        material_doc.material_code = matnr
        material_doc.save(ignore_permissions=True)

        requestor_doc.db_set("zmsg", zmsg or "")
        requestor_doc.db_set("ztext", ztext or "")
        requestor_doc.db_set("maktx", maktx or "")
        requestor_doc.db_set("approval_status", "Code Generated by SAP")
        requestor_doc.save(ignore_permissions=True)

        log = frappe.new_doc("MO SAP Logs")
        log.requestor_ref_no = requestor_doc.name
        log.erp_to_sap_data = "NA"
        log.sap_response = json.dumps(data, indent=2)
        log.direction = "SAP to ERP"
        log.save(ignore_permissions=True)

        frappe.db.commit()
        send_email_from_sap(requestor_doc, matnr, maktx, zmsg, ztext)

        return {
            "status": "success",
            "updated_material_code": matnr,
            "material_master": material_master_name
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "SAP Material Code Update Error")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def send_email_from_sap(requestor_doc, matnr, maktx, zmsg, ztext):
    try:
        # print("Email Function Hit")

        to_email = requestor_doc.contact_information_email
        if not to_email:
            frappe.log_error("No recipient email found", f"Requestor: {requestor_doc.name}")
            return {"status": "fail", "message": _("No recipient email found")}

        cc_emails = []
        
        reporting_to_id = requestor_doc.immediate_reporting_head
        user_name = frappe.get_value("Employee Master", filters={"name": requestor_doc.requested_by}, fieldname=["full_name"])
        
        if reporting_to_id:
            employee_doc = frappe.get_doc("Employee Master", reporting_to_id)
            if employee_doc.email:
                cc_emails.append(employee_doc.email)
        
       

        subject = f"Material Code Created for Request ID {requestor_doc.request_id}"
        
        message = f"""
            <p>Dear {user_name or 'User'},</p>
            <p>Greetings for the Day!</p>
            <p>SAP has successfully created a material for your request.</p>
            <p><strong>Details:</strong></p>
            <ul>
                <li><b>Request ID:</b> {requestor_doc.request_id}</li>
                <li><b>Material Code:</b> {matnr}</li>
                <li><b>Description:</b> {maktx}</li>
                <li><b>Message:</b> {zmsg}</li>
                <li><b>Details:</b> {ztext}</li>
            </ul>
            <p>Thanking you,<br/>SAP Integration Team</p>
        """

        frappe.custom_sendmail(
            recipients=[to_email],
            cc=cc_emails,
            subject=subject,
            message=message,
            now=True
        )

        # print("Email sent successfully.")
        return {"status": "success", "message": _("Email sent successfully")}

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "SAP Email Sending Error")
        return {"status": "fail", "message": _("Failed to send email.")}
    

