MATERIAL_FIELDS = {
        "storage_location": "storage_location",
        "division": "division",
        "old_material_code": "old_material_code",
        "material_group": "material_group",
        "batch_requirements_yn": "batch_requirements_yn",
        "brand_make": "brand_make",
        "availability_check": "availability_check",
        "class_type": "class_type",
        "class_number": "class_number",
        "serial_number_profile": "serial_number_profile",
        "serialization_level": "serialization_level",
        "purchase_uoms": "purchase_uom",
        "numerator_purchase_uom": "numerator_purchase_uom",
        "denominator_purchase_uom": "denominator_purchase_uom",
        "lead_time": "lead_time",
        "mrp_type": "mrp_type",
        "mrp_group": "mrp_group",
        "mrp_controller_revised": "mrp_controller_revised",
        "lot_size_key": "lot_size_key",
        "procurement_type": "procurement_type",
        "scheduling_margin_key": "scheduling_margin_key",
        "issue_unit": "issue_unit",
        "numerator_issue_uom": "numerator_issue_uom",
        "denominator_issue_uom": "denominator_issue_uom",
        "material_code_revised": "material_code_revised",
        "material_code": "material_code",
        "industry": "industry",
        "purchase_order_text": "purchase_order_text",
        "purchasing_group": "purchasing_group",
        "gr_processing_time": "gr_processing_time",
        "purchasing_value_key": "purchasing_value_key",
        "min_lot_size": "min_lot_size",
        
    }

MATERIAL_ONBOARDING_FIELDS = {
        "material_information": "material_information",
        "minimum_remaining_shell_life": "minimum_remaining_shell_life",
        "total_shell_life": "total_shell_life",
        "expiration_date": "expiration_date",
        "inspection_interval": "inspection_interval",
        "incoming_inspection_01": "incoming_inspection_01",
        "incoming_inspection_09": "incoming_inspection_09",
        "material_specifications": "material_specifications",
        "valuation_class": "valuation_class",
        "profit_center": "profit_center",
        "price_control": "price_control",
        "hsn_code": "hsn_code",
        "do_not_cost": "do_not_cost",
        "comment_by_store": "comment_by_store",
        "intended_usage_application": "intended_usage_application",
        "storage_requirements": "storage_requirements",
        "hazardous_material": "hazardous_material",
        "inspection_require": "inspection_require",
        "approval_date": "approval_date",
        "approval_status": "approval_status",
        "requested_by_name": "requested_by_name",
        "requested_by_place": "requested_by_place",
        "approved_by_name": "approved_by_name",
        "approved_by_place": "approved_by_place",
        "hsn_status": "hsn_status",
        "special_instructionsnotes": "special_instructionsnotes",
        "lot_size": "lot_size",
        "lead_time": "lead_time",
        "purchase_order_text": "purchase_order_text"
    }




MO_ERP_TO_SAP_FIELD_MAP = {
    "material_code_revised": "Matnr",
    "material_name_description": "Maktx",
    "purchase_uom": "Bstme",
    "issue_unit": "Ausme",
    "availability_check": "Mtvfp",
    "batch_requirements_yn": "Xchpf",
    "lead_time": "Plifz",
    "mrp_type": "Dismm",
    "mrp_group": "Disgr",
    "mrp_controller_revised": "Dispo",
    "lot_size_key": "Disls",
    "procurement_type": "Beskz",
    "scheduling_margin_key": "Fhori",
    "purchase_order_text": "Purcom",
    "purchasing_group": "Ekgrp",
    "gr_processing_time": "Webaz",
    "purchasing_value_key": "Ekwsl",
    "minimum_remaining_shell_life": "Mhdrz",
    "total_shell_life": "Mhdhb",
    "expiration_date": "Iprkz",
    "inspection_interval": "Prfrq",
    "incoming_inspection_01": "Qminst",
    "incoming_inspection_09": "Qminst1",
    "valuation_class": "Bklas",
    "profit_center": "Prctr",
    "price_control": "Vprsv",
    "do_not_cost": "Ncost",
    "comment_by_store": "Storecom",
    "inspection_require": "Qmatv",
    "class_type": "Class",
    "class_number": "Klart",
    "serial_number_profile": "Sernp",
    "serialization_level": "Serlv",
    "storage_location": "Lgort",
    "division": "Spart",
}